CI: Use cache correctly

diff --git a/.github/workflows/UnitTests.yml b/.github/workflows/UnitTests.yml
--- a/.github/workflows/UnitTests.yml
+++ b/.github/workflows/UnitTests.yml
@@ -99,14 +99,6 @@ jobs:
       with:
         version: ${{ matrix.julia_version }}
 
-    - name: Switch to dev version of MPItrampoline_jll
-      run: |
-        # This adds the desired version of `MPItrampoline_jll`
-        # successfully, but then fails to precompile `MPI`. We don't
-        # care about this failure here. Later on, precompiling `MPI`
-        # should succeed.
-        julia --project=@. -e 'using Pkg; Pkg.add(url="https://github.com/eschnett/MPItrampoline_jll.jl")' || true
-
     # https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484
     - name: Cache artifacts
       uses: actions/cache@v1
@@ -119,6 +111,14 @@ jobs:
           ${{ runner.os }}-test-${{ env.cache-name }}-
           ${{ runner.os }}-test-
           ${{ runner.os }}-
+
+    - name: Switch to dev version of MPItrampoline_jll
+      run: |
+        # This adds the desired version of `MPItrampoline_jll`
+        # successfully, but then fails to precompile `MPI`. We don't
+        # care about this failure here. Later on, precompiling `MPI`
+        # should succeed.
+        julia --project=@. -e 'using Pkg; Pkg.add(url="https://github.com/eschnett/MPItrampoline_jll.jl")' || true
 
     - uses: julia-actions/julia-buildpkg@latest
     - uses: julia-actions/julia-runtest@latest
